apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-data
  namespace: development
spec:
  storageClassName: "standard"
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
