name: Hello Pipeline

on:
  push:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello"

      - name: Show System Info
        run: uname -a

      - name: Check NodeJS Version
        run:  node --version
